### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by C-BJ** [inanevin/LinaEngine#59]
**"Lina_critical": identifier not found** ------------------------------------------in LinaCommon, LinaAudio and LinaGraphics
**#error:  Exactly one of NDEBUG and _DEBUG needs to be defined!** -------in LinaPhysics and LinaEditor
**Unable to open the file ".. \ lib \ debug, release \ linaeditor. Lib"**----------in sandbox

It wasn't like this before. I don't know why

**Comment by C-BJ** [comment]
After replacing the C + + version, the error is more specific. I'm trying to solve it

**Comment by C-BJ** [comment]
My attempt failed😢

**Comment by inanevin** [comment]
Can you share the complete error stack, your platform, compiler etc.?

**Comment by C-BJ** [comment]
> Can you share the complete error stack, your platform, compiler etc., basically any more information you can provide.

This is basically all the error information I can provide. For the first error, the IDE can jump, but the compilation will report an error

Windows11 1000.22000.652.0
Windows10SDK 10.0.19041.0
MSVC V142
cmake version 3.23.2
@inanevin

**Comment by C-BJ** [comment]
Have you checked my reply in https://github.com/inanevin/LinaEngine/issues/56?

**Comment by inanevin** [comment]
> > Can you share the complete error stack, your platform, compiler etc., basically any more information you can provide.
> 
> This is basically all the error information I can provide. For the first error, the IDE can jump, but the compilation will report an error
> 
> Windows11 1000.22000.652.0 Windows10SDK 10.0.19041.0 MSVC V142 cmake version 3.23.2 @inanevin

Did you make any modifications to CMake options? Also can you search project-wide for "Lina_critical", it's either MSVC is false reporting in the error log, or you are somehow using an old version of the logging system. I assume it's master-branch with latest changes pulled?

**Comment by C-BJ** [comment]
I found the problem. This command cannot be followed by both debug and release
`cmake -DLINA_ENABLE_LOGGING:BOOL=OFF -DLINA_ENABLE_PROFILING:BOOL=OFF -DCMAKE_CONFIGURATION_TYPES:STRING="Debug,Release"`

**Comment by C-BJ** [comment]
The external release compiler error is solved here: https://github.com/inanevin/LinaEngine/pull/61

**Comment by inanevin** [comment]
This doesn't solve the compile error, only blocks CMake configuration to assume that there's a Debug config. It can't be used in your commit as there will be Debug config related CMake code that'll never pass because of that.
